-- Backup from Render Database
-- Date: 2026-02-01T17:54:43.937Z

-- Criteria
INSERT INTO criteria (key, name, weight) VALUES ('ai_quantum_use', 'Use of AI / Quantum Computing', 15.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('code_quality', 'Code Quality & Extensibility', 10.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('innovation', 'Innovation & Creativity', 15.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('performance', 'Performance & Result Quality', 10.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('presentation', 'Presentation & Teamwork', 10.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('problem_importance', 'Problem & Importance', 15.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('sdgs', 'UN Sustainable Development Goals (SDGs)', 10.00) ON CONFLICT (key) DO NOTHING;
INSERT INTO criteria (key, name, weight) VALUES ('social_impact', 'Social Impact', 15.00) ON CONFLICT (key) DO NOTHING;

-- Users
INSERT INTO users (id, name, email, password, role, hall) VALUES (1, 'Admin User', 'admin@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'admin', NULL);
INSERT INTO users (id, name, email, password, role, hall) VALUES (2, 'Judge A1', 'judge_a1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (3, 'Judge A2', 'judge_a2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (4, 'Judge A3', 'judge_a3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (5, 'Judge A4', 'judge_a4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (6, 'Judge A5', 'judge_a5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (7, 'Judge B1', 'judge_b1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (8, 'Judge B2', 'judge_b2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (9, 'Judge B3', 'judge_b3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (10, 'Judge B4', 'judge_b4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (11, 'Judge B5', 'judge_b5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (12, 'Judge C1', 'judge_c1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (13, 'Judge C2', 'judge_c2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (14, 'Judge C3', 'judge_c3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (15, 'Judge C4', 'judge_c4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (16, 'Judge C5', 'judge_c5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (17, 'Judge D1', 'judge_d1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (18, 'Judge D2', 'judge_d2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (19, 'Judge D3', 'judge_d3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (20, 'Judge D4', 'judge_d4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (21, 'Judge D5', 'judge_d5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'judge', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (22, 'Team A1', 'team_a1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (23, 'Team A2', 'team_a2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (24, 'Team A3', 'team_a3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (25, 'Team A4', 'team_a4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (26, 'Team A5', 'team_a5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (27, 'Team A6', 'team_a6@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (28, 'Team A7', 'team_a7@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (29, 'Team A8', 'team_a8@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (30, 'Team A9', 'team_a9@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (31, 'Team A10', 'team_a10@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (32, 'Team A11', 'team_a11@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (33, 'Team A12', 'team_a12@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (34, 'Team A13', 'team_a13@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (35, 'Team A14', 'team_a14@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (36, 'Team A15', 'team_a15@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (37, 'Team A16', 'team_a16@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (38, 'Team A17', 'team_a17@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (39, 'Team A18', 'team_a18@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (40, 'Team A19', 'team_a19@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (41, 'Team A20', 'team_a20@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'A');
INSERT INTO users (id, name, email, password, role, hall) VALUES (42, 'Team B1', 'team_b1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (43, 'Team B2', 'team_b2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (44, 'Team B3', 'team_b3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (45, 'Team B4', 'team_b4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (46, 'Team B5', 'team_b5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (47, 'Team B6', 'team_b6@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (48, 'Team B7', 'team_b7@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (49, 'Team B8', 'team_b8@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (50, 'Team B9', 'team_b9@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (51, 'Team B10', 'team_b10@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (52, 'Team B11', 'team_b11@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (53, 'Team B12', 'team_b12@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (54, 'Team B13', 'team_b13@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (55, 'Team B14', 'team_b14@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (56, 'Team B15', 'team_b15@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (57, 'Team B16', 'team_b16@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (58, 'Team B17', 'team_b17@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (59, 'Team B18', 'team_b18@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (60, 'Team B19', 'team_b19@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (61, 'Team B20', 'team_b20@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'B');
INSERT INTO users (id, name, email, password, role, hall) VALUES (62, 'Team C1', 'team_c1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (63, 'Team C2', 'team_c2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (64, 'Team C3', 'team_c3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (65, 'Team C4', 'team_c4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (66, 'Team C5', 'team_c5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (67, 'Team C6', 'team_c6@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (68, 'Team C7', 'team_c7@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (69, 'Team C8', 'team_c8@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (70, 'Team C9', 'team_c9@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (71, 'Team C10', 'team_c10@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (72, 'Team C11', 'team_c11@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (73, 'Team C12', 'team_c12@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (74, 'Team C13', 'team_c13@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (75, 'Team C14', 'team_c14@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (76, 'Team C15', 'team_c15@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (77, 'Team C16', 'team_c16@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (78, 'Team C17', 'team_c17@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (79, 'Team C18', 'team_c18@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (80, 'Team C19', 'team_c19@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (81, 'Team C20', 'team_c20@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'C');
INSERT INTO users (id, name, email, password, role, hall) VALUES (82, 'Team D1', 'team_d1@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (83, 'Team D2', 'team_d2@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (84, 'Team D3', 'team_d3@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (85, 'Team D4', 'team_d4@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (86, 'Team D5', 'team_d5@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (87, 'Team D6', 'team_d6@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (88, 'Team D7', 'team_d7@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (89, 'Team D8', 'team_d8@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (90, 'Team D9', 'team_d9@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (91, 'Team D10', 'team_d10@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (92, 'Team D11', 'team_d11@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (93, 'Team D12', 'team_d12@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (94, 'Team D13', 'team_d13@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (95, 'Team D14', 'team_d14@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (96, 'Team D15', 'team_d15@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (97, 'Team D16', 'team_d16@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (98, 'Team D17', 'team_d17@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (99, 'Team D18', 'team_d18@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (100, 'Team D19', 'team_d19@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');
INSERT INTO users (id, name, email, password, role, hall) VALUES (101, 'Team D20', 'team_d20@khakathon.com', '$2a$10$3/r8NR66WdDyrqnqUlNHI.lTdCnwJZF8jvtg3x3fjxCNtbVY28LjK', 'team', 'D');

-- Teams
INSERT INTO teams (id, user_id, hall) VALUES (1, 22, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (2, 23, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (3, 24, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (4, 25, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (5, 26, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (6, 27, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (7, 28, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (8, 29, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (9, 30, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (10, 31, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (11, 32, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (12, 33, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (13, 34, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (14, 35, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (15, 36, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (16, 37, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (17, 38, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (18, 39, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (19, 40, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (20, 41, 'A');
INSERT INTO teams (id, user_id, hall) VALUES (21, 42, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (22, 43, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (23, 44, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (24, 45, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (25, 46, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (26, 47, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (27, 48, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (28, 49, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (29, 50, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (30, 51, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (31, 52, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (32, 53, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (33, 54, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (34, 55, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (35, 56, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (36, 57, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (37, 58, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (38, 59, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (39, 60, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (40, 61, 'B');
INSERT INTO teams (id, user_id, hall) VALUES (41, 62, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (42, 63, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (43, 64, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (44, 65, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (45, 66, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (46, 67, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (47, 68, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (48, 69, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (49, 70, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (50, 71, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (51, 72, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (52, 73, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (53, 74, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (54, 75, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (55, 76, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (56, 77, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (57, 78, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (58, 79, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (59, 80, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (60, 81, 'C');
INSERT INTO teams (id, user_id, hall) VALUES (61, 82, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (62, 83, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (63, 84, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (64, 85, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (65, 86, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (66, 87, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (67, 88, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (68, 89, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (69, 90, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (70, 91, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (71, 92, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (72, 93, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (73, 94, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (74, 95, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (75, 96, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (76, 97, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (77, 98, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (78, 99, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (79, 100, 'D');
INSERT INTO teams (id, user_id, hall) VALUES (80, 101, 'D');

-- Judges
INSERT INTO judges (id, user_id, hall) VALUES (1, 2, 'A');
INSERT INTO judges (id, user_id, hall) VALUES (2, 3, 'A');
INSERT INTO judges (id, user_id, hall) VALUES (3, 4, 'A');
INSERT INTO judges (id, user_id, hall) VALUES (4, 5, 'A');
INSERT INTO judges (id, user_id, hall) VALUES (5, 6, 'A');
INSERT INTO judges (id, user_id, hall) VALUES (6, 7, 'B');
INSERT INTO judges (id, user_id, hall) VALUES (7, 8, 'B');
INSERT INTO judges (id, user_id, hall) VALUES (8, 9, 'B');
INSERT INTO judges (id, user_id, hall) VALUES (9, 10, 'B');
INSERT INTO judges (id, user_id, hall) VALUES (10, 11, 'B');
INSERT INTO judges (id, user_id, hall) VALUES (11, 12, 'C');
INSERT INTO judges (id, user_id, hall) VALUES (12, 13, 'C');
INSERT INTO judges (id, user_id, hall) VALUES (13, 14, 'C');
INSERT INTO judges (id, user_id, hall) VALUES (14, 15, 'C');
INSERT INTO judges (id, user_id, hall) VALUES (15, 16, 'C');
INSERT INTO judges (id, user_id, hall) VALUES (16, 17, 'D');
INSERT INTO judges (id, user_id, hall) VALUES (17, 18, 'D');
INSERT INTO judges (id, user_id, hall) VALUES (18, 19, 'D');
INSERT INTO judges (id, user_id, hall) VALUES (19, 20, 'D');
INSERT INTO judges (id, user_id, hall) VALUES (20, 21, 'D');

-- Projects

-- Evaluations
INSERT INTO evaluations (id, judge_id, team_id) VALUES (1, 1, 20);
INSERT INTO evaluations (id, judge_id, team_id) VALUES (2, 1, 1);
INSERT INTO evaluations (id, judge_id, team_id) VALUES (14, 2, 1);
INSERT INTO evaluations (id, judge_id, team_id) VALUES (15, 1, 11);
INSERT INTO evaluations (id, judge_id, team_id) VALUES (16, 1, 10);
INSERT INTO evaluations (id, judge_id, team_id) VALUES (17, 1, 18);
INSERT INTO evaluations (id, judge_id, team_id) VALUES (19, 1, 13);

-- Evaluation Scores
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (1, 2, 'problem_importance', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (2, 2, 'ai_quantum_use', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (3, 2, 'sdgs', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (4, 2, 'innovation', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (5, 2, 'social_impact', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (6, 2, 'code_quality', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (7, 2, 'performance', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (8, 2, 'presentation', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (49, 1, 'problem_importance', 10.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (50, 1, 'ai_quantum_use', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (51, 1, 'sdgs', 10.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (52, 1, 'innovation', 10.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (53, 1, 'social_impact', 10.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (54, 1, 'code_quality', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (55, 1, 'performance', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (56, 1, 'presentation', 7.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (73, 14, 'problem_importance', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (74, 14, 'ai_quantum_use', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (75, 14, 'sdgs', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (76, 14, 'innovation', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (77, 14, 'social_impact', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (78, 14, 'code_quality', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (79, 14, 'performance', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (80, 14, 'presentation', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (81, 15, 'problem_importance', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (82, 15, 'ai_quantum_use', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (83, 15, 'sdgs', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (84, 15, 'innovation', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (85, 15, 'social_impact', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (86, 15, 'code_quality', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (87, 15, 'performance', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (88, 15, 'presentation', 9.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (89, 16, 'problem_importance', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (90, 16, 'ai_quantum_use', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (91, 16, 'sdgs', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (92, 16, 'innovation', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (93, 16, 'social_impact', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (94, 16, 'code_quality', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (95, 16, 'performance', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (96, 16, 'presentation', 0.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (97, 17, 'problem_importance', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (98, 17, 'ai_quantum_use', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (99, 17, 'sdgs', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (100, 17, 'innovation', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (101, 17, 'social_impact', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (102, 17, 'code_quality', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (103, 17, 'performance', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (104, 17, 'presentation', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (113, 19, 'problem_importance', 3.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (114, 19, 'ai_quantum_use', 3.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (115, 19, 'sdgs', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (116, 19, 'innovation', 2.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (117, 19, 'social_impact', 5.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (118, 19, 'code_quality', 8.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (119, 19, 'performance', 7.00);
INSERT INTO evaluation_scores (id, evaluation_id, criterion_key, score) VALUES (120, 19, 'presentation', 9.00);

-- Reset Sequences
SELECT setval('users_id_seq', 101, true);
SELECT setval('teams_id_seq', 80, true);
SELECT setval('judges_id_seq', 20, true);
SELECT setval('evaluations_id_seq', 19, true);
SELECT setval('evaluation_scores_id_seq', 120, true);
